version: "3.3"  # optional since v1.27.0
services:
    main:
        image: main:latest
        build:
            context: .
            args: 
                PATH_ARG: ${PATH_MAIN:-/home/azureuser/lm_performance_test}
        environment:
            TEST_CONFIG_PATH: ${TEST_CONFIG_PATH:-.TestsConfig/Configuration.json}
            LC_RDB_LOGIN: ${LC_RDB_LOGIN:-}
            LC_RDB_PASS: ${LC_RDB_PASS:-}
            LC_STRESS_KEY_JMETER_VM: ${LC_STRESS_KEY_JMETER_VM:-}
            LC_STRESS_KEY_RDB: ${LC_STRESS_KEY_RDB:-}
            LC_USER_SYSTEM: ${LC_USER_SYSTEM:-azureuser}
            POSTGRESS_CONTAINER_NAME: ${POSTGRESS_CONTAINER_NAME:-revdebug-server-docker-compose_postgres_1}
            RDB_HOST: ${RDB_HOST:-}
            RDB_DB: ${RDB_DB:-revdebug_db}
            RDB_USER: ${RDB_USER:-rdb_user}
            RDB_PASS: ${RDB_PASS:-masterkey}
            RDB_PORT_DB: ${RDB_PASS:-5432}
            RDB_USER_SYSTEM: ${RDB_USER_SYSTEM:-azureuser}
            REVDEBUG_AUTH: ${REVDEBUG_AUTH:-E56D341B29AC483B}
            REVDEBUG_SERVER_NAME: ${REVDEBUG_SERVER_NAME:-}
            REVDEBUG_CERTIFICATE_NAME: ${REVDEBUG_CERTIFICATE_NAME:-}
            REVDEBUG_DOCKER_TAG: ${REVDEBUG_DOCKER_TAG:-}
            KEYCLOAK_ACTIVE: ${KEYCLOAK_ACTIVE:-0}
            LC_STRESS_KEY_APP: ${LC_STRESS_KEY_APP:-}
            APP_USER_SYSTEM: ${APP_USER_SYSTEM:-azureuser}
            APPS_PATH: ${APPS_PATH:-~/stress}

            DATA_DB: ${DATA_DB:-}
            DATA_DB_USER: ${DATA_DB_USER:-}
            DATA_DB_PASS: ${DATA_DB_PASS:-}
            DATA_DB_PORT: ${DATA_DB_PORT:-}
            DATA_DB_KEY: ${DATA_DB_KEY:-}
            DATA_DB_HOST: ${DATA_DB_HOST:-}
            DATA_DB_SERVER_HOST: ${DATA_DB_HOST:-}
            DATA_DB_SERVER_USER: ${DATA_DB_HOST:-azureuser}
        volumes:
            - ./:/app
        networks:
            static-network:
                ipv4_address: 172.20.128.3

    AioHttp3.8:
        image: aiohttp-py-3.8
        build: 
            context: DataGenerationApp/
        ports:
            - 8080:8080
        environment:
            REVDEBUG_APM: 1
            REVDEBUG_RELEASE: GoStressTest
            REVDEBUG_VERSION: GoStressTest
            REVDEBUG_HOST: ${REVDEBUG_HOST:-20.199.127.147}
            REVDEBUG_SOLUTION: DataGeneration
            REVDEBUG_APPLICATION: DataGeneration
        volumes:
            - ./DataGenerationApp/:/app/
        logging:
            driver: none
        networks:
            static-network:
                ipv4_address: 172.20.128.2
    jmmaster:
        container_name: master
        image: jm-master:latest
        build:
            context:  docker-jm/jm-master/
        tty: true
        stdin_open: true
        volumes:
            - ./TestResult:/testJM
            - ./TestStart:/testJMStart
        network_mode: "bridge"
    slave0:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave1:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave2:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave3:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave4:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave5:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave6:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
