version: "3.3"  
services:
    main:
        image: main:latest
        build:
            context: .
        environment:
            - JSON_CONFIG=${JSON_CONFIG}
            - MODEL_TEST_FILE=${MODEL_TEST_FILE}
        volumes:
            - .:/app