version: "3.3"  # optional since v1.27.0
services:
    main:
        image: main:latest
        build:
            context: .
            args: 
                PATH_ARG: ${PATH_MAIN:-/home/ubuntu/lm_performance_test}
        environment:
            TEST_CONFIG_PATH: ${TEST_CONFIG_PATH:-.TestsConfig/Configuration.json}
            LC_RDB_LOGIN: ${LC_RDB_LOGIN:-}
            LC_RDB_PASS: ${LC_RDB_PASS:-}
            LC_STRESS_KEY_JMETER_VM: ${LC_STRESS_KEY_JMETER_VM:-}
            LC_STRESS_KEY_RDB: ${LC_STRESS_KEY_RDB:-}
            LC_USER_SYSTEM: ${LC_USER_SYSTEM:-ubuntu}
            POSTGRESS_CONTAINER_NAME: ${POSTGRESS_CONTAINER_NAME:-revdebug-server-docker-compose_postgres_1}
            RDB_HOST: ${RDB_HOST:-}
            RDB_DB: ${RDB_DB:-revdebug_db}
            RDB_USER: ${RDB_USER:-rdb_user}
            RDB_PASS: ${RDB_PASS:-masterkey}
            RDB_PORT_DB: ${RDB_PASS:-5432}
            RDB_USER_SYSTEM: ${RDB_USER_SYSTEM:-ubuntu}
            REVDEBUG_AUTH: ${REVDEBUG_AUTH:-E56D341B29AC483B}
            REVDEBUG_SERVER_NAME: ${REVDEBUG_SERVER_NAME:-}
            REVDEBUG_CERTIFICATE_NAME: ${REVDEBUG_CERTIFICATE_NAME:-}
            REVDEBUG_DOCKER_TAG: ${REVDEBUG_DOCKER_TAG:-}
            KEYCLOAK_ACTIVE: ${KEYCLOAK_ACTIVE:-0}
            LC_STRESS_KEY_APP: ${LC_STRESS_KEY_APP:-}
            APP_USER_SYSTEM: lm
            APPS_PATH: ${APPS_PATH:-~/stress}
            PATH_: ${PATH_MAIN:-~/}

            DATA_DB: ${DATA_DB:-}
            DATA_DB_USER: ${DATA_DB_USER:-}
            DATA_DB_PASS: ${DATA_DB_PASS:-}
            DATA_DB_PORT: ${DATA_DB_PORT:-}
            DATA_DB_KEY: ${DATA_DB_KEY:-}
            DATA_DB_HOST: ${DATA_DB_HOST:-}
            DATA_DB_SERVER_HOST: ${DATA_DB_HOST:-}
            DATA_DB_SERVER_USER: ${DATA_DB_HOST:-ubuntu}
        volumes:
            - ./:/app

    jmmaster:
        container_name: master
        image: jm-master:latest
        build:
            context:  docker-jm/jm-master/
        tty: true
        stdin_open: true
        volumes:
            - ./TestResult:/testJM
            - ./TestStart:/testJMStart
        network_mode: "bridge"
    slave0:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave1:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave2:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave3:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave4:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave5:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
    slave6:
        image: jm-slave:latest
        build:
            context: docker-jm/jm-slave/
        network_mode: "bridge"
        logging:
            driver: none
